# Generated by Django 3.2.6 on 2021-09-02 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_feedbackform'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=200, null=True)),
                ('reciept', models.CharField(max_length=200, null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
