# Generated by Django 3.2.6 on 2021-09-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_payworkshop_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payworkshop',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
